### ISSUE TITLE
Consistency issues

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#12]
DSH/BTC pair has problems across exchanges (HitBTC and BTC-e). There are also some other problematic pairs I've seen over the time with big differences between exchanges. Could you please investigate closer into problematic pairs?

I suggest testing each pair across all exchanges and see if there's big bid/ask/last fluctuation between exchanges.

**Comment by kroitor** [comment]
Sure, thanks for helping me with this. I'm rewriting the tests to cover all of that you mentioned, in the middle of the process right now. The tests would probably run continuously, and we will have a public gh-page or a standalone webpage with the results up to date. I already have scripts to calculate cross-market correlation, so testing all pairs on all exchanges is not very hard to do, though it may take some time to integrate our test framework.

**Comment by kroitor** [comment]
I have fixed that `DSH → DASH` inconsistency. Seems to be a problem with Bitfinex, HitBTC and BTCe. Closing down this issue, will investigate further and fix everything suspicious.

**Comment by kroitor** [comment]
I also added a section on [Naming Consistency](https://github.com/kroitor/ccxt/wiki/Manual#naming-consistency) to the ccxt Manual in case somebody encounters same problems with another exchange.

**Comment by nmiculinic** [comment]
HitBTC is still not fixed. It get's wrong value for DASH/BTC pair

**Comment by kroitor** [comment]
The HitBTC exchange seems to return the following occasionally:
<img width="600" alt="screen shot 2017-07-12 at 00 10 56" src="https://user-images.githubusercontent.com/1294454/28090914-b132d574-6696-11e7-960d-baea5c683269.png">
Fixing this now.

**Comment by kroitor** [comment]
@nmiculinic can you please specify what's wrong with the value of DASH/BTC, because when I run tests, nothing seems out of the order. I need to reproduce this bug.

<img width="1040" alt="screen shot 2017-07-12 at 00 40 59" src="https://user-images.githubusercontent.com/1294454/28092076-d0e61a9e-669a-11e7-883d-130b1caffac2.png">
