### ISSUE TITLE
A low price is submitted in exponential format

### ISSUE THREAD

**Issue by TearsOfTheEarth** [kroitor/ccxt#122]
Hi,

There is an issue I will demonstrate on example, here is the call:
yobit.create_limit_buy_order('DOGE/BTC', buyAmount, **0.00000039**)
And the actual request is:
method=Trade&pair=doge_btc&type=buy&amount=25589.86897998&**rate=3.9e-07**
That confuses the exchange:
ccxt.ExchangeError: yobit {"success":0,"error":"Total transaction amount is less than minimal total: 0.00010000"}

I have fixed this with a temporary fix similar to the below (as yobit operates with 8 digits after the decimal point):
yobit.create_limit_buy_order('DOGE/BTC', buyAmount, "{:.8f}".format(0.00000039))
But need to think about proper permanent solution.

**Comment by kroitor** [comment]
Thanks for submitting this report! We already have a solution to this, will upload a fix to it very soon.

**Comment by kroitor** [comment]
The solution is to call self.decimal (price), like in the following snippet:
```Python
    def create_order(self, market, type, side, amount, price=None, params={}):
        self.loadMarkets()
        if type == 'market':
            raise ExchangeError(self.id + ' allows limit orders only')
        response = self.tapiPostTrade(self.extend({
            'pair': self.market_id(market),
            'type': side,
            'amount': amount,
            'rate': self.decimal(price), # ← here
        }, params))
        return {
            'info': response,
            'id': str(response['return']['order_id']),
        }
```

This is now fixed and available in v.1.4.17+.
Thanks again!

**Comment by kroitor** [comment]
Please reopen this issue or let us know if you experience the same difficulty with any other exchange. Thanks!

**Comment by TearsOfTheEarth** [comment]
Hi Igor,

Thanks for the prompt response but this did not fix it, have the same issue with the new version.

**Comment by kroitor** [comment]
@TearsOfTheEarth hi! One sec, I'll take a look.

**Comment by kroitor** [comment]
Ok, I think I fixed it, will be available in a new version very soon.

**Comment by kroitor** [comment]
Ok, should be working normally in 1.4.29+, thx a lot for reporting!

**Comment by TearsOfTheEarth** [comment]
The same issue is applicable to HitBTC.

**Comment by kroitor** [comment]
@TearsOfTheEarth ok, we will now fix it for HitBTC as well. Thanks for the feedback!
