### ISSUE TITLE
Problems with HitBTC clientOrderId

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#155]
Hi.
I am using your latest version and I was trying to make a limit buy order on HitBTC.

The error that pops out is 
```
ccxt.errors.ExchangeNotAvailable: hitbtc POST http://api.hitbtc.com/api/1/trading/new_order?nonce=6154297&apikey=****&clientOrderId=6154297&symbol=ETHBTC&side=buy&quantity=7&type=limit&price=0.0756940000 409 Conflict  {"code":"InvalidArgument","message":"Fields are not valid: clientOrderId"}
```

The thing is, I overrided the nonce() method so that now it returns something smaller than the 8 digit number that they require.
In HitBTC `create_order(..)` method could you replace the line
`clientOrderId = self.nonce()`
with something from here 
https://docs.python.org/3/library/uuid.html

So that everyone who's using it gets good results.
Thank you.
Good luck.

**Comment by kroitor** [comment]
The thing is, I overrided the nonce() method so that now it returns something smaller than the 8 digit number that they require.
> In HitBTC create_order(..) method could you replace the line
> clientOrderId = self.nonce()

Yes )

> with something from here
> https://docs.python.org/3/library/uuid.html

No, because we have to make it portable, but we will add something like an overrideable createClientOrderId () method, so that you could work around this.

And, as always, thanks for posting this! We will fix it very soon.

**Comment by kroitor** [comment]
This is fixed in version 1.5.14+. No changes in your code are required, you can simply update the library and continue ) Thank you very much for reporting this!

**Comment by marinsokol5** [comment]
Version ccxt-1.5.21
HitBTC createOrder `clientOrderId = self.nonce()`.

Just in case you forgot to upload :) .

**Comment by kroitor** [comment]
@marinsokol5 no, I didn't forget to upload. That's strange, because I really did and that line should read clientOrderId = self.milliseconds (). Could you please check your version once again?

See:
https://github.com/kroitor/ccxt/blob/master/ccxt/exchanges.py#L9515

**Comment by marinsokol5** [comment]
Yup my side.
I upgraded it but PyCharm was a bit slow at updating it.
Thank you.

**Comment by kroitor** [comment]
Thx for reporting back!
