### ISSUE TITLE
Gdax function request

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#20]
Check method request in python code in  class GDAX.
Your latest version.
Im using python 3.6.
You called your function hash with 4 parameters.It takes only 3.

I have tried sending what+ secret.decode() as first parameter but it just sends another error.

https://pastebin.com/RDRaFqsr

**Comment by kroitor** [comment]
Thanks for reporting! Investigating into this now.

**Comment by kroitor** [comment]
I've fixed the typo, could you please test it again with your keys and report? Thank you!

**Comment by marinsokol5** [comment]
https://pastebin.com/hKxKCm3D

Yes unfortunately there is still an error.
secret are bytes and they are being encoded in the method for hmac
I have chnaged secrets.decode() before calling the method but then pops out

https://pastebin.com/t0jG3jvS

I am sorry i don't know how to fix it.
If you need any more data or testing let me know.

**Comment by kroitor** [comment]
Ok, after some intensive debugging, I found the root of the problem at last, fixing it now. Will upload and update on this whenever it's done (might take up to a day to fix for all markets that are subject to this issue). Thanks again for your involvement!

**Comment by marinsokol5** [comment]
You are the best man.

**Comment by kroitor** [comment]
This problem with GDAX must be gone now. Please update your ccxt library version and report if anything else is wrong with it. I've tested it and it should work.
